app:
  scheduler:
    enable: true
    interval: "PT30S"
    force-check-delay: "PT30M"
  stack-overflow-client:
    base-url: "https://api.stackexchange.com"
    retry:
      codes: [ 408, 429, 502, 503, 504 ]
      strategy: exponential
      delay: 1s
      max-attempts: 10
  github-client:
    base-url: "https://api.github.com"
    retry:
      codes: [ 408, 429, 502, 503, 504 ]
      strategy: exponential
      delay: 1s
      max-attempts: 10
  bot-client:
    base-url: "http://localhost:8090"
    retry:
      codes: [ 408, 429, 502, 503, 504 ]
      strategy: exponential
      delay: 1s
      max-attempts: 10
  database-access-type: jpa

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  liquibase:
    enabled: false
  jooq:
    sql-dialect: Postgres
  jpa:
    show-sql: true
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    strategy: first
    rate-limits:
    - cache-key: getRemoteAddr()
      post-execute-condition: getStatus() eq 200
      bandwidths:
      - capacity: 100
        time: 1
        unit: hours
        refill-speed: interval
