app:
  scheduler:
    enable: true
    interval: "PT10M"
    force-check-delay: "PT30M"
  stack-overflow-client:
    base-url: "https://api.stackexchange.com"
  github-client:
    base-url: "https://api.github.com"
  bot-client:
    base-url: "http://localhost:8090"

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  liquibase:
    enabled: false

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
