app:
  telegram-token: ${BOT_TOKEN}
  scrapper-client:
    base-url: "http://localhost:8080"
    retry:
      codes: [408, 429, 502, 503, 504]
      strategy: exponential
      delay: 1s
      max-attempts: 10

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      strategy: first
      rate-limits:
        - cache-key: getRemoteAddr()
          post-execute-condition: getStatus() eq 200
          bandwidths:
            - capacity: 2
              time: 1
              unit: hours
              refill-speed: interval
